//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CACertBundleReference) DeepCopyInto(out *CACertBundleReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CACertBundleReference.
func (in *CACertBundleReference) DeepCopy() *CACertBundleReference {
	if in == nil {
		return nil
	}
	out := new(CACertBundleReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CACertSecretReference) DeepCopyInto(out *CACertSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CACertSecretReference.
func (in *CACertSecretReference) DeepCopy() *CACertSecretReference {
	if in == nil {
		return nil
	}
	out := new(CACertSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerConfig) DeepCopyInto(out *ListenerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerConfig.
func (in *ListenerConfig) DeepCopy() *ListenerConfig {
	if in == nil {
		return nil
	}
	out := new(ListenerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPGatewayExtension) DeepCopyInto(out *MCPGatewayExtension) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPGatewayExtension.
func (in *MCPGatewayExtension) DeepCopy() *MCPGatewayExtension {
	if in == nil {
		return nil
	}
	out := new(MCPGatewayExtension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPGatewayExtension) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPGatewayExtensionList) DeepCopyInto(out *MCPGatewayExtensionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPGatewayExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPGatewayExtensionList.
func (in *MCPGatewayExtensionList) DeepCopy() *MCPGatewayExtensionList {
	if in == nil {
		return nil
	}
	out := new(MCPGatewayExtensionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPGatewayExtensionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPGatewayExtensionSpec) DeepCopyInto(out *MCPGatewayExtensionSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.BackendPingIntervalSeconds != nil {
		in, out := &in.BackendPingIntervalSeconds, &out.BackendPingIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.TrustedHeadersKey != nil {
		in, out := &in.TrustedHeadersKey, &out.TrustedHeadersKey
		*out = new(TrustedHeadersKey)
		**out = **in
	}
	if in.SessionStore != nil {
		in, out := &in.SessionStore, &out.SessionStore
		*out = new(SessionStore)
		**out = **in
	}
	if in.OAuthProtectedResource != nil {
		in, out := &in.OAuthProtectedResource, &out.OAuthProtectedResource
		*out = new(OAuthProtectedResource)
		(*in).DeepCopyInto(*out)
	}
	if in.CACertBundleRef != nil {
		in, out := &in.CACertBundleRef, &out.CACertBundleRef
		*out = new(CACertBundleReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPGatewayExtensionSpec.
func (in *MCPGatewayExtensionSpec) DeepCopy() *MCPGatewayExtensionSpec {
	if in == nil {
		return nil
	}
	out := new(MCPGatewayExtensionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPGatewayExtensionStatus) DeepCopyInto(out *MCPGatewayExtensionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPGatewayExtensionStatus.
func (in *MCPGatewayExtensionStatus) DeepCopy() *MCPGatewayExtensionStatus {
	if in == nil {
		return nil
	}
	out := new(MCPGatewayExtensionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPGatewayExtensionTargetReference) DeepCopyInto(out *MCPGatewayExtensionTargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPGatewayExtensionTargetReference.
func (in *MCPGatewayExtensionTargetReference) DeepCopy() *MCPGatewayExtensionTargetReference {
	if in == nil {
		return nil
	}
	out := new(MCPGatewayExtensionTargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerRegistration) DeepCopyInto(out *MCPServerRegistration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerRegistration.
func (in *MCPServerRegistration) DeepCopy() *MCPServerRegistration {
	if in == nil {
		return nil
	}
	out := new(MCPServerRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPServerRegistration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerRegistrationList) DeepCopyInto(out *MCPServerRegistrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPServerRegistration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerRegistrationList.
func (in *MCPServerRegistrationList) DeepCopy() *MCPServerRegistrationList {
	if in == nil {
		return nil
	}
	out := new(MCPServerRegistrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPServerRegistrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerRegistrationSpec) DeepCopyInto(out *MCPServerRegistrationSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.CredentialRef != nil {
		in, out := &in.CredentialRef, &out.CredentialRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.CACertSecretRef != nil {
		in, out := &in.CACertSecretRef, &out.CACertSecretRef
		*out = new(CACertSecretReference)
		**out = **in
	}
	if in.TokenURLElicitation != nil {
		in, out := &in.TokenURLElicitation, &out.TokenURLElicitation
		*out = new(TokenURLElicitationConfig)
		**out = **in
	}
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerRegistrationSpec.
func (in *MCPServerRegistrationSpec) DeepCopy() *MCPServerRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(MCPServerRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerRegistrationStatus) DeepCopyInto(out *MCPServerRegistrationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerRegistrationStatus.
func (in *MCPServerRegistrationStatus) DeepCopy() *MCPServerRegistrationStatus {
	if in == nil {
		return nil
	}
	out := new(MCPServerRegistrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPVirtualServer) DeepCopyInto(out *MCPVirtualServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPVirtualServer.
func (in *MCPVirtualServer) DeepCopy() *MCPVirtualServer {
	if in == nil {
		return nil
	}
	out := new(MCPVirtualServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPVirtualServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPVirtualServerList) DeepCopyInto(out *MCPVirtualServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPVirtualServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPVirtualServerList.
func (in *MCPVirtualServerList) DeepCopy() *MCPVirtualServerList {
	if in == nil {
		return nil
	}
	out := new(MCPVirtualServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPVirtualServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPVirtualServerSpec) DeepCopyInto(out *MCPVirtualServerSpec) {
	*out = *in
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Prompts != nil {
		in, out := &in.Prompts, &out.Prompts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPVirtualServerSpec.
func (in *MCPVirtualServerSpec) DeepCopy() *MCPVirtualServerSpec {
	if in == nil {
		return nil
	}
	out := new(MCPVirtualServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthProtectedResource) DeepCopyInto(out *OAuthProtectedResource) {
	*out = *in
	if in.AuthorizationServers != nil {
		in, out := &in.AuthorizationServers, &out.AuthorizationServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BearerMethodsSupported != nil {
		in, out := &in.BearerMethodsSupported, &out.BearerMethodsSupported
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ScopesSupported != nil {
		in, out := &in.ScopesSupported, &out.ScopesSupported
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthProtectedResource.
func (in *OAuthProtectedResource) DeepCopy() *OAuthProtectedResource {
	if in == nil {
		return nil
	}
	out := new(OAuthProtectedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionStore) DeepCopyInto(out *SessionStore) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionStore.
func (in *SessionStore) DeepCopy() *SessionStore {
	if in == nil {
		return nil
	}
	out := new(SessionStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenURLElicitationConfig) DeepCopyInto(out *TokenURLElicitationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenURLElicitationConfig.
func (in *TokenURLElicitationConfig) DeepCopy() *TokenURLElicitationConfig {
	if in == nil {
		return nil
	}
	out := new(TokenURLElicitationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustedHeadersKey) DeepCopyInto(out *TrustedHeadersKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustedHeadersKey.
func (in *TrustedHeadersKey) DeepCopy() *TrustedHeadersKey {
	if in == nil {
		return nil
	}
	out := new(TrustedHeadersKey)
	in.DeepCopyInto(out)
	return out
}
